var GAME_LEVELS = [

  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                           ",
   "                                                                                                                  ",
   "                                                           xxxxxxx                                                ",
   "     xxx                                                   x!!!!!x                                           xxx  ",
   "     x                        o              o             xxxvxxx                                             x  ",
   "     x                                      xxx      o                              o      o      o            x  ",
   "     x                 o                            xxx                                                        x  ",
   "     x                xxx        xxxxxxxx                                                                      x  ",
   "     x       @  o     x x        x      x                            o   o   o                               o x  ",
   "     xxxbbxxxxxxxxxxxxx xxxxxxxxxx      x!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx   bbb    bbb    bbb    xxxxxxxx  ",
   "                                        x!!!!!!!!!!!!!!!!!x                    x                        x         ",
   "                                        x!!!!!!!!!!!!!!!!!x                    x                        x         ",
   "                                        x!!!!!!!!!!!!!!!!!x                    xxxxxxxxxxxxxxxxxxxxxxxxxx         ",
   "                                        x!!!!!!!!!!!!!!!!!x                                                       "],
   
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                     o                                        ",
   "                                                                                                              ",
   "                                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxx                ",
   "                                                                   x                                          ",
   "                                                                   x                                          ",
   "                                                                   x                                          ",
   "                                                             b     x                                          ",
   "                                                                   x                                          ",
   "                                                                   x                                          ",
   "                                                                   x                                          ",
   "                                                                   x                                          ",
   "                                                     b             x                                          ",
   "                   o                                               x                                          ",
   "                   xxxxxxxxxxxxx  x                                x                                          ",
   "                    x             x                                x                                          ",
   "                    x=      o     x   o                            x                                          ",
   "                   oxxxx  xxxxxxxxx  xxx    b                      x                                          ",
   "                   xx                x x                           x                                          ",
   "                    x        o       x x                           x                                          ",
   "                    xxxxxxxxxxxxxxxxxx x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " xxx               ox                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " x                 xx                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " x                 x                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " x                 x                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " x      @      o   x                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   " xxxxxxxxxxxxxxxxxxx                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   "                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          ",
   "                                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          "],
  ["                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                            x                                  xxxxxxxxx",
   "                                            x                                  xxxxxxxxx",
   "                                            x                                  xxxxxxxxx",
   "                                                  |                            xxxxxxxxx",
   "                                                      |                             |  x",
   "                                             o            | o       o                  x",
   "                                            xxxxx       o   x | o   x        xxxxxx    x",
   "                                            xxx     o   x       x |     o      xxx     x",
   "                                            xxx     x                 | x      xxx     x",
   "                                            xxx                           |    xxx    xx",
   "                                    xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     x",
   "                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x",
   "                                    x!xxxxxxxxxxxxxxxxxxxxxx!xxxxxxx!xxxxxxx!xxxxxx    x",
   "                                    x!xxxxxxxxxxxxxxxx     xvx     xvx     xvx         x",
   "                                    xvx     xxxxxxxxxx                                 x",
   "                                            xxxxxxxxxx                              xxxx",
   "                                            xxxxxxxxxx          o               o   xxxx",
   "                 o         o         o                         xxx             xxxxxxxxx",
   "                                                                                       x",
   "                                                   o                    o              x",
   "                      z                       xxxxxx                   xxx             x",
   "            @                               xxxxxxxxxx                                 x",
   "          xxxxx     xxxxx     xxxxx     xxxxxxxxxxxxxxxxxx      o               o      x",
   "!!!!!!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxxxxxxxxxxxxxxx     xxx             xxx     x",
   "!!!!!!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxxxxxxxxxxxxxxx                             x",
   "!!!!!!!!!!xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
